import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Scale, FileText, HelpCircle, Users, CheckCircle } from 'lucide-react';

const TermsConditions = () => {
  return (
    <div className="max-w-4xl mx-auto py-10 px-4 sm:px-6 lg:px-8 space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col gap-4 border-b border-slate-200 pb-6">
        <Link to="/" className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-400 hover:text-slate-700 transition-colors w-fit">
          <ArrowLeft className="h-4 w-4" /> Back to Home
        </Link>
        <div className="flex items-center gap-3">
          <div className="h-12 w-12 rounded-2xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-brand-indigo shrink-0">
            <Scale className="h-6 w-6" />
          </div>
          <div>
            <h1 className="font-display text-3xl font-black text-slate-900">Terms of Service</h1>
            <p className="text-slate-400 text-xs mt-1">Last Updated: June 17, 2026</p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200 shadow-sm space-y-8 text-slate-600 leading-relaxed text-sm">
        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle className="h-4 w-4 text-brand-indigo" /> 1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using TripCraft AI, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not access or use the application or its modules.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold text-slate-900 flex items-center gap-2">
            <Users className="h-4 w-4 text-brand-indigo" /> 2. Account Registration
          </h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials (email and password). You agree to notify us immediately of any unauthorized access. We are not liable for any loss resulting from unauthorized use of your account.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold text-slate-900 flex items-center gap-2">
            <FileText className="h-4 w-4 text-brand-indigo" /> 3. Document Uploads & Public Sharing
          </h2>
          <ul className="list-disc pl-5 space-y-1.5 text-xs text-slate-500">
            <li><strong>Document Ownership:</strong> You retain all ownership rights to any travel confirmation files (flight tickets, lodging bookings) uploaded to our servers.</li>
            <li><strong>OCR Content Scan:</strong> You grant us a temporary license to process your uploaded files to extract text data for your itineraries.</li>
            <li><strong>Public Sharing:</strong> When generating public sharing links (e.g. `shareId` links), your itinerary is viewable by anyone possessing that unique ID. You accept responsibility for information published via shared links.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold text-slate-900 flex items-center gap-2">
            <HelpCircle className="h-4 w-4 text-brand-indigo" /> 4. generative AI Limitations (Disclaimer)
          </h2>
          <p>
            TripCraft AI processes itinerary requests using artificial intelligence models. Because AI outputs are generated algorithmically:
          </p>
          <ul className="list-disc pl-5 space-y-1.5 text-xs text-slate-500">
            <li>We do not guarantee the completeness, accuracy, or real-time availability of locations, hours, or travel recommendations generated by the assistant.</li>
            <li>Travel details (including flight status, hotel coordinates, restaurant pricing, and directions) should be independently verified before you travel.</li>
            <li>We are not responsible for any travel disruptions, booking errors, financial losses, or physical accidents resulting from reliance on AI recommendations.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="font-display text-lg font-bold text-slate-900 flex items-center gap-2">
            5. Termination
          </h2>
          <p>
            We reserve the right to suspend or terminate your account and access to the services at our sole discretion, without notice, for conduct that violates these Terms or is harmful to other users or our platform integrity.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsConditions;
